export const CONST_PROJECTS = [
  {
    year: 2024,
    project: "FMC Dashboard",
    madeAt: "SALT",
    buildWith: [
      "AngularJs",
      "TypeScript",
      "HTML",
      "SCSS",
      "RXJS",
      "Angular Material",
      "Tailwind CSS",
      "Jest",
    ],
    isFavorite: false,
    role: "Middle Frontend Engineer",
    description:
      "Contributed to the development and improvement of the FMC Dashboard user interface, including features such as reward management and broadcast management. This project utilized AngularJs, TypeScript, SCSS, and Tailwind CSS to ensure optimal performance and responsive design. Unit testing was conducted with Jest to maintain code quality.",
    image: "https://dummyimage.com/600x400/000/fff.png",
  },
  {
    year: 2024,
    project: "TSurvey",
    madeAt: "SALT",
    buildWith: [
      "AngularJs",
      "TypeScript",
      "HTML",
      "SCSS",
      "RXJS",
      "Angular Material",
      "Tailwind CSS",
      "Jest",
    ],
    link: {
      alias: "TSurvey",
      href: "https://tsurvey.id/",
    },
    isFavorite: true,
    role: "Middle Frontend Engineer",
    description:
      "Developed generative AI features for administrators and surveyors, while revamping modules such as gender, age, and respondent location targeting. This project used AngularJs, TypeScript, Angular Material, and Tailwind CSS to create a seamless user experience.",
    image: "/images/tsurvey.png",
  },
  {
    year: 2023,
    project: "Octo Smart",
    madeAt: "CIMB Niaga",
    buildWith: [
      "ReactJs",
      "React Native",
      "TypeScript",
      "HTML",
      "CSS",
      "Redux",
    ],
    link: {
      alias: "Octo Smart",
      href: "https://alphasft.cimbniaga.co.id/",
    },
    isFavorite: true,
    role: "Middle Frontend Engineer",
    description:
      "Built the Octo Smart mobile and tablet applications, focusing on features like Sunlife Report and CR Lending. The project was developed using ReactJs, React Native, and Redux, ensuring compatibility and smooth performance across devices.",
    image: "https://dummyimage.com/600x400/000/fff.png",
  },
  {
    year: 2022,
    project: "Haioo",
    madeAt: "Telkom Indonesia",
    buildWith: [
      "ReactJs",
      "NextJs",
      "TypeScript",
      "HTML",
      "CSS",
      "Tailwind CSS",
      "React Query",
    ],
    link: {
      alias: "Haioo",
      href: "https://play.google.com/store/apps/details?id=id.co.telkom.tnt.haioo&hl=id",
    },
    isFavorite: true,
    role: "Junior Frontend Engineer",
    description:
      "Developed and optimized the Haioo CMS and landing page using ReactJs, NextJs, and Tailwind CSS. Integrated React Query to enable efficient data management.",
    image: "/images/haioo.png",
  },
  {
    year: 2022,
    project: "Marketplace Twibbonize",
    madeAt: "Twibbonize",
    buildWith: ["NextJs", "TypeScript", "HTML", "CSS", "Tailwind CSS", "Redux"],
    link: {
      alias: "Twibbonize",
      href: "https://marketplace.twibbonize.com/",
    },
    isFavorite: true,
    role: "Junior Frontend Engineer",
    description:
      "Created the Twibbonize Marketplace using NextJs, Redux Toolkit, and Tailwind CSS. This project included API integration and collaboration with backend and digital marketing teams.",
    image: "/images/marketplace_twibbonize.png",
  },
  {
    year: 2022,
    project: "CRM Contact Loyalty",
    madeAt: "Kalbe",
    buildWith: ["NextJs", "TypeScript", "HTML", "CSS", "Tailwind CSS", "Redux"],
    isFavorite: false,
    role: "Junior Frontend Engineer",
    description:
      "Developed a CMS for a loyalty management system using NextJs, Redux, and SCSS. This project focused on enhancing customer relationship management with an intuitive interface.",
    image: "https://dummyimage.com/600x400/000/fff.png",
  },
];
